<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <title><xsl:value-of select="/rss/channel/title"/> — RSS feed</title>
        <style>
          :root { color-scheme: light dark; }
          * { box-sizing: border-box; }
          body {
            font-family: 'Inter Variable', Inter, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
            max-width: 760px;
            margin: 0 auto;
            padding: 3rem 1.5rem 4rem;
            line-height: 1.55;
            color: #111;
            background: #fafafa;
          }
          @media (prefers-color-scheme: dark) {
            body { color: #e8e8ea; background: #0f0f10; }
            .item { border-color: #2a2a2d; }
            .item a { color: #7cb3ff; }
            .note { background: #1a1a1e; border-color: #2a2a2d; }
          }
          header { margin-bottom: 2rem; }
          .eyebrow {
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            opacity: 0.6;
            margin-bottom: 0.5rem;
          }
          h1 { font-size: 1.75rem; margin: 0 0 0.5rem; letter-spacing: -0.02em; }
          .desc { opacity: 0.8; margin: 0 0 1rem; }
          .note {
            font-size: 0.875rem;
            padding: 0.75rem 1rem;
            border: 1px solid #e4e4e7;
            border-radius: 8px;
            background: #fff;
            margin-bottom: 2rem;
          }
          .note code {
            font-family: 'JetBrains Mono Variable', ui-monospace, monospace;
            font-size: 0.85em;
          }
          .item {
            padding: 1.25rem 0;
            border-top: 1px solid #e4e4e7;
          }
          .item:last-child { border-bottom: 1px solid #e4e4e7; }
          .item h2 { margin: 0 0 0.25rem; font-size: 1.125rem; }
          .item h2 a {
            color: inherit;
            text-decoration: none;
          }
          .item h2 a:hover { text-decoration: underline; }
          .item time { font-size: 0.8rem; opacity: 0.6; }
          .item p { margin: 0.5rem 0 0; opacity: 0.85; }
          footer {
            margin-top: 3rem;
            font-size: 0.8rem;
            opacity: 0.6;
            text-align: center;
          }
          footer a { color: inherit; }
        </style>
      </head>
      <body>
        <header>
          <div class="eyebrow">RSS feed</div>
          <h1><xsl:value-of select="/rss/channel/title"/></h1>
          <p class="desc"><xsl:value-of select="/rss/channel/description"/></p>
          <div class="note">
            This is an RSS feed. Copy the URL of this page into your feed reader to subscribe.
            Or visit <a href="/"><xsl:value-of select="/rss/channel/link"/></a>.
          </div>
        </header>
        <xsl:for-each select="/rss/channel/item">
          <article class="item">
            <h2><a><xsl:attribute name="href"><xsl:value-of select="link"/></xsl:attribute><xsl:value-of select="title"/></a></h2>
            <time><xsl:value-of select="substring(pubDate, 1, 16)"/></time>
            <p><xsl:value-of select="description"/></p>
          </article>
        </xsl:for-each>
        <footer>
          Generated by Astro. <a href="/">Back to site</a>.
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
